[flavor]
# dark = "catppuccin-frappe-lavender"
# light = "catppuccin-frappe-lavender"

# dark = "catppuccin-macchiato-lavender"
# light = "catppuccin-macchiato-lavender"

# dark = "catppuccin-macchiato-green"
# light = "catppuccin-macchiato-green"

dark = "catppuccin-macchiato-teal"
light = "catppuccin-macchiato-teal"

# dark = "catppuccin-macchiato-pink"
# light = "catppuccin-macchiato-pink"
